name: container-management-system

services:
    backend:
        build: ./backend
        restart: unless-stopped
        ports:
            - "3000:3000/tcp"
        volumes:
            - ./backend/.env.prod:/usr/src/app/.env
            - /var/run/docker.sock:/var/run/docker.sock
            - ./backend/access.log:/usr/src/app/access.log
        user: root
        command: sh -c "npx prisma migrate deploy && npm run start"

    frontend:
        build: ./frontend
        restart: unless-stopped
        ports:
            - "8000:3000/tcp"
        volumes:
            - ./frontend/.env.prod:/usr/src/app/.env

    postgresql:
        image: bitnami/postgresql:latest
        restart: unless-stopped
        ports:
            - "5432:5432/tcp"
        volumes:
            - pg-data:/bitnami/postgresql
        environment:
            - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
            - POSTGRESQL_LOG_HOSTNAME=true
            - POSTGRESQL_REPLICATION_MODE=master
            - POSTGRESQL_REPLICATION_USER=repl_user
            - POSTGRESQL_REPLICATION_PASSWORD=repl_user
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_DATABASE=container-management
        labels:
            - "com.centurylinklabs.watchtower.enable=false"

    redis:
        image: bitnami/redis:latest
        restart: unless-stopped
        ports:
            - "6379:6379/tcp"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        labels:
            - "com.centurylinklabs.watchtower.enable=false"

volumes:
    pg-data:
